Initalise node_properties outside the for loop.
So that it is initalised for the case where the first for loop is _not_ 
entered and the second for loop _is_ entered. In that case (when a 
SemiStructuredNode has no defined properties) an error would occur when 
calling save():

UnboundLocalError: local variable 'node_properties' referenced before 
assignment

... or a similar variation depending on your luck.